/* USER */

export const albumPhotoListConst = {
  GET_ALBUM_PHOTO_LIST: "GET_ALBUM_PHOTO_LIST",
  GET_ALBUM_PHOTO_LIST_SUCCESS: "GET_ALBUM_PHOTO_LIST_SUCCESS",
  GET_ALBUM_PHOTO_LIST_FAILED: "GET_ALBUM_PHOTO_LIST_FAILED",
};
